version: '3.1'
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: insights
            POSTGRES_USER: insights
            POSTGRES_DB: insights
        ports: 
            - "5432:5432"
    web:
        build: .
        restart: always
        command: bash -c "pipenv run ./manage.py migrate --noinput && pipenv run gunicorn -b 0.0.0.0:8000 insights.wsgi"
        environment:
            DB_HOST: db
        ports:
            - "8000:8000"
        depends_on:
            - db
